### PCB Ops Example Template
### Gitlab CI_CD 

image:
  name: akshmakov/pcb-cicd:latest


stages:
  - rules
  - build
  - release
  - post-release


erc:
  stage: build
  script:
    - make ci_erc
  when: always
  artifacts:
    paths:
      - output/


  
drc:
  stage: build
  script:
    - make ci_drc
  when: always
  artifacts:
    paths:
      - output/


project_outputs:
  stage: build
  script:
    - make ci_plot
    - make ci_sch
    - make ci_drawings
    - make ci_step
    - make ci_bom
    - make ci_pnp
  when: always
  artifacts:
    paths:
      - output/


rfq:
  stage: release
  only:
    - master
    - release/*
    - tags
  script:
    - make ci_rfq
  artifacts:
    paths:
      - output/

